### ISSUE TITLE
TC and VM selected but SMS results still include maplink

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#410]
**Describe the bug**
TC and VM are selected yet the meeting results still show a maplink in the results. No physical address is shown but the Google map link is shown.  Interestingly enough if you click on it it doesn't take you to the location, it just calls the google maps app.
![image](https://user-images.githubusercontent.com/29008815/78997972-03a46f00-7b8b-11ea-81f0-8ddd72138ea7.png)

**What version are you running?**
3.7.0 beta2

**Did this happen on prior versions to the one you are running?**
This feature is new for this version.

**To Reproduce**
1. SMS location where you know there are meetings closed
2. Check results Address is hiddent but Google Maplink still shows (FYI include_map_link is set to true in the config). 

**Expected behavior**
My expectation is that if the meeting is temporarily closed and the physical address is hidden the maplink should not be included in the results as its no longer relevant.
**Screenshots**
added above

**Comment by radius314** [comment]
fixed in 3.7.0-beta3

**Comment by brustar64** [comment]
Confirmed as fixed.
We have a small issue were temporary virtual meetings have been created by Areas to provide an online presence for all their physical meetings and this still shows a map link.  The use case for this is limited and we expect temporary so we can live with a maplink against this small quotient of meetings.  What I don't understand is that the map link doesn't open in the defined location in Google maps on my phone.  It simply opens in my current location.  Does anyone else have this issue on Yap returns?

**Comment by radius314** [comment]
I have heard of that bug before.

**Comment by radius314** [comment]
Ok I have a patch for this, if you want to test again: https://archives.bmlt.app/yap/yap-1497-85bacf2f4d3d9ba3c80cba4473d9454b80dc3818.zip

**Comment by brustar64** [comment]
Its still showing the map link for meetings that are location centric online meetings.
The issue exists in the current version as well.  I think we need something that hides the map link when we check the virtual format.  I think its TC that currently is the map link hide trigger. VM should ideally hide it as well to allow these new location centric online meetings to output without a map link.  If you search the Australian DB there are a number of examples.  - https://www.na.org.au/multi/victoria-area/
Look for the Melbourne based NA@Home meetings.

**Comment by radius314** [comment]
The only trigger for hiding the map link is `TC`.  There is no other trigger.  If that is not working then this is a bug.

**Comment by radius314** [comment]
@brustar64 do you have a sample of meeting that is VM and TC that is showing a map link?

**Comment by brustar64** [comment]
> @brustar64 do you have a sample of meeting that is VM and TC that is showing a map link?

No I don't.  Its working well now thank you.
