### ISSUE TITLE
Meeting Search calls do not show in Reports section of the UI

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/yap#594]
### Description
* Meeting search calls _sometimes_ show in the metrics chart portion of the reporting UI. In my testing, they work for the Capital Area, and do not work for North Dade Area.
* Meeting search calls _never_ show in the datatable portion of the UI. This is reproducible with both Capital Area and North Dade areas.

### Reproduction
**Capital Area**

When someone calls the Capital Area number (984-204-7091) and performs a meeting search:
* I see hits to status.php in the logs, indicating status callbacks are configured.
* I see some entires in the `records` table.
* I see Meeting Search data in the metrics chart.
* I **DO NOT** see Meeting Search data in the datatable.

**North Dade Area**

When someone calls the North Dade Area number (866-935-8811) and performs a meeting search:
* I see hits to status.php in the logs, indicating status callbacks are configured.
* I see some entires in the `records` table.
* I **DO NOT** see Meeting Search data in the metrics chart.
* I **DO NOT** see Meeting Search data in the datatable.

**Comment by dgershman** [comment]
ack... investigating.

**Comment by dgershman** [comment]
I could repro.  The data is there, it’s a bug with the report query.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dgershman** [comment]
still refactoring

**Comment by jbraswell** [comment]
thx u 4 ur service

**Comment by dgershman** [comment]
Fixed in yap 4.1.0-beta2

**Comment by jbraswell** [comment]
I still can't get meeting search calls to show up for the capital area number on the sezf server.

Number is 1-877-590-6262.
Call webhook is https://bmlt.sezf.org/zonal-yap/?override_service_body_id=95&override_sms_combine=true&override_jft_option=false.
Call status changes url is https://bmlt.sezf.org/zonal-yap/status.php?override_service_body_id=95&override_sms_combine=true.

**Comment by jbraswell** [comment]
You can disregard previous comment, it looks like SMS and Call meeting searches are now showing up in the UI

**Comment by dgershman** [comment]
completed, released in 4.1.0
